"""Publish a deep plan (generated by ``deep_plan``) to Basecamp.

One to-do list, each sprint a group, each ticket a rich, assigned, due-dated
todo (story/design/build/test/vibe/trust in the description), plus the three
documents (Requirements, Architecture, Build Guide) into the project's Docs &
Files. Reuses the Basecamp primitives in ``project_plan_reconciler`` /
``basecamp_build_writer`` so posts are authored as the operator.
"""
from __future__ import annotations

import html
import logging
import re
from datetime import timedelta

logger = logging.getLogger(__name__)

# Program week each sprint occupies. 9-week build (weeks 3–11); week 12 = presentations.
WEEK_SPAN = {"s0": (3, 3), "s1": (4, 4), "s2": (5, 6), "s3": (7, 8), "s4": (9, 10), "s5": (11, 11)}
_ANCHOR_OFFSET_DAYS = 14  # cohort-start Monday → Monday of week 3 (≈ "week 2.5 Monday")


def anchor_from_cohort_start(cohort_start_monday):
    """The first due-date Monday (start of program week 3)."""
    return cohort_start_monday + timedelta(days=_ANCHOR_OFFSET_DAYS)


def _weekdays(a, b):
    d, out = a, []
    while d <= b:
        if d.weekday() < 5:
            out.append(d)
        d += timedelta(days=1)
    return out


def _due_dates(n, key, anchor):
    ws, we = WEEK_SPAN.get(key, (3, 3))
    days = _weekdays(anchor + timedelta(days=(ws - 3) * 7), anchor + timedelta(days=(we - 3) * 7 + 4))
    if not days or n <= 0:
        return [None] * max(n, 0)
    return [days[min(len(days) - 1, round(i * (len(days) - 1) / max(1, n - 1)))].isoformat() for i in range(n)]


def _esc(s):
    return html.escape(str(s or ""))


def _ticket_html(t):
    rows = [("Story", t.get("story")), ("Owner agent", t.get("agent")), ("Design", t.get("design")),
            ("Build", t.get("build")), ("Test — done when", t.get("test")),
            ("Vibe-code it", t.get("vibe")), ("Trust (TBI)", t.get("tbi"))]
    return "<br><br>".join(f"<strong>{k}:</strong> {_esc(v)}" for k, v in rows if v)


def _md_html(md):
    out = []
    for line in (md or "").split("\n"):
        l = line.rstrip()
        if not l:
            out.append("<br>"); continue
        m = re.match(r"(#{1,4})\s+(.*)", l)
        if m:
            lvl = min(len(m.group(1)), 3)
            out.append(f"<h{lvl}>{_esc(m.group(2))}</h{lvl}>"); continue
        if l.lstrip().startswith(("- ", "* ")):
            out.append(f"<li>{_esc(l.lstrip()[2:])}</li>"); continue
        body = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", _esc(l))
        out.append(f"<div>{body}</div>")
    return "".join(out)


def publish_deep_plan(plan, user, bc_project_id, anchor_monday, list_name, project_name=""):
    """Create the BC todolist + sprint groups + tickets, and the 3 documents.

    Returns {todolist_id, created, docs}.
    """
    from execution.products.library import mcp_tools
    from execution.advisory import basecamp_build_writer as bw
    from execution.advisory import project_plan_reconciler as rec

    name = project_name or plan.get("project", "Project")
    assignee = bw.resolve_operator_bc_person_id(user, bc_project_id)
    todoset = rec._discover_todoset(user, bc_project_id)
    overview = f"{name} - deep build plan (maker/checker-generated). Requirements / Architecture / Build Guide in Docs & Files."
    list_id = rec._create_todolist(user, bc_project_id, todoset, list_name, overview)

    created = 0
    for sp in (plan.get("tickets") or {}).get("sprints", []):
        ws, we = WEEK_SPAN.get(sp.get("key"), (3, 3))
        wlabel = f" (wk {ws}" + (f"-{we}" if we != ws else "") + ")"
        gid = rec._create_group(user, bc_project_id, list_id, f"{sp.get('key', '').upper()} - {sp.get('title', '')}{wlabel}")
        tks = sp.get("tickets", [])
        for t, due in zip(tks, _due_dates(len(tks), sp.get("key"), anchor_monday)):
            content = (str(t.get("title", "")) + (f"  [{t['agent']}]" if t.get("agent") else ""))[:230]
            rec._create_todo(user, bc_project_id, gid, content, _ticket_html(t), [assignee] if assignee else [], due)
            created += 1

    doc_ids = []
    try:
        acct = mcp_tools._bc_account()
        proj = mcp_tools._bc_request("GET", f"https://3.basecampapi.com/{acct}/projects/{bc_project_id}.json", user=user)
        vault = next((d.get("id") for d in proj.get("dock", []) if d.get("name") == "vault"), None)
        if vault:
            for title, key in (("Requirements", "requirements"), ("Architecture & Design", "architecture"), ("Build Guide", "build_guide")):
                md = plan.get(key)
                if not md:
                    continue
                r = mcp_tools._bc_request(
                    "POST", f"https://3.basecampapi.com/{acct}/buckets/{bc_project_id}/vaults/{vault}/documents.json",
                    payload={"title": f"{name} - {title}", "content": _md_html(md), "status": "active"}, user=user)
                doc_ids.append(r.get("id") if isinstance(r, dict) else None)
    except Exception as e:  # docs are non-blocking — the tickets are the build
        logger.warning(f"[deep_plan] document publish failed (non-blocking): {e}")

    return {"todolist_id": list_id, "created": created, "docs": doc_ids}
